# settings.toml

# The unique identifier for this pod [uint]
SONOCHAPEL_POD_ID = 1

# WiFi access point
CIRCUITPY_WIFI_SSID = "SonoFan"
CIRCUITPY_WIFI_PASSWORD = "itchyo237"

# The server to which the pod sends its messages via UDP
SONOCHAPEL_SERVER_IPADDR = "192.168.0.23"
SONOCHAPEL_SERVER_PORT = 12345

# Delay after sending pod messages, in milliseconds [uint]
SONOCHAPEL_MSG_DELAY = 0

# PN532 timeout to detect an RFID tag, in milliseconds [uint]
SONOCHAPEL_RFID_TIMEOUT = 100

# sendINFO() actually sends only if >= this INFO_LEVEL
SONOCHAPEL_INFO_LEVEL = -999

#eof
