# settings.toml

# WiFi access point
CIRCUITPY_WIFI_SSID = "SonoFan"
CIRCUITPY_WIFI_PASSWORD = "itchyo237"

# The unique identifier for this pod [uint]
SONOCHAPEL_POD_ID = 1

# Delay between pod's DATA messages, in milliseconds [uint]
SONOCHAPEL_POD_INTERVAL = 0

# PN532 timeout to detect an RFID tag, in milliseconds [uint]
SONOCHAPEL_RFID_TIMEOUT = 100

# Where the pod send its messages via UDP
SONOCHAPEL_SERVER_IPADDR = "192.168.0.23"
SONOCHAPEL_SERVER_PORT = 12345

#eof
