# settings.toml

# The unique identifier for this pod [uint]
SONOCHAPEL_POD_ID = 99

# WiFi access point
CIRCUITPY_WIFI_SSID = "SonoFan"
CIRCUITPY_WIFI_PASSWORD = "itchyo237"

# The server to which the pod sends its messages via UDP
SONOCHAPEL_SERVER_IPADDR = "192.168.0.116"
SONOCHAPEL_SERVER_PORT = 53187

# Delay after sending each pod message, in milliseconds [uint]
SONOCHAPEL_MSG_DELAY = 0

# PN532 timeout to detect an RFID tag, in milliseconds [uint]
SONOCHAPEL_RFID_TIMEOUT = 100

# sendINFO() only sends message if its level is >= this value
SONOCHAPEL_INFO_LEVEL = 0

# Brightness of the LEDs, 0 (off) to 100 (full) [uint]
SONOCHAPEL_LED_BRIGHTNESS = 10

#eof
